# Generated by Django 4.2.11 on 2024-07-11 12:23

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.ManyToManyField(to='product.color')),
                ('size', models.ManyToManyField(to='product.size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_item',
            field=models.ForeignKey(default=builtins.print, on_delete=django.db.models.deletion.CASCADE, to='product.warehouseitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='warehouse_item',
            field=models.ForeignKey(default=builtins.print, on_delete=django.db.models.deletion.CASCADE, to='product.warehouseitem'),
            preserve_default=False,
        ),
    ]
