# Generated by Django 5.0.6 on 2024-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='new collection', max_length=300, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
